[package]
name = "sysinfo"
version = "0.1.0"
authors = ["Spooky Sec <anonymousbot100110@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sys-info = "0.9"
